version: "3.10"
services:
  fivemsrv:
    build: .
    restart: always
    ports:
      - "30120:30120"
      - "30120:30120/udp"
      - "127.0.0.1:40120:40120"
    volumes:
      - "./data:/fivem/txData"
    depends_on:
      - fivemdb
    links:
      - fivemdb

  fivemdb:
    image: mariadb:11
    restart: always
    ports:
      - "127.0.0.1:43306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: gtadbrootpw
    volumes:
      - "./database:/var/lib/mysql"
